#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

# Source utility functions.
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH

LOG_FILE="${OPENSHIFT_LOG_DIR}"

#LOG_FILE="${OPENSHIFT_DIY_LOG_DIR}play.log"

#chmod +x ${OPENSHIFT_REPO_DIR}target/universal/stage/bin/${OPENSHIFT_APP_NAME}

echo ${JAVA_HOME}&>> $LOG_FILE
echo "!!!"
echo ${JAVA_HOME}
echo ${PATH}

source "$OPENSHIFT_REPO_DIR/.openshift/lib/utils"

# Start Tomcat 7.
start_tomcat7
echo [Start finished \\o/]
